// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ennhknwwfdlaudephyly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVubmhrbnd3ZmRsYXVkZXBoeWx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MDE2OTcsImV4cCI6MjA2MTM3NzY5N30.mUjr8q-mzD13u2AuLsR2ZXkMD46Iuy7hIUkF3sSYwxs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);